# 模拟电商订单数据分析


> 需求：创建5行5列1-100的随机数组，完成【切片、修改、添加、删除、查找】全流程

In [ ]:
import numpy as np

In [ ]:
# 创建一个5行5列1-100的随机数组
np.random.seed(100)
arr = np.random.randint(1, 101, size=(5, 5))
print(f"原始订单数据:\n {arr}")

In [ ]:
# 获取前三个订单的前三项数据
arr_slice = arr[:3, :3].copy()
print(f"前三个订单的前三项数据:\n {arr_slice}")

In [ ]:
# 修改切片中，大于50的元素，将其设为50
arr_slice[arr_slice > 50] = 50
print(f"修改后的前三个订单的前三项数据:\n {arr_slice}")

In [ ]:
# 新增一笔订单数据
arr_new = np.append(arr, [[100]*5], axis=0)
print(f"新增一笔订单数据后的:\n {arr_new}")

In [12]:
# 删除第5行订单数据
arr_new = np.delete(arr_new, 5, axis=0)
print(f"删除第三行订单数据后的:\n {arr_new}")

删除第三行订单数据后的:
 [[ 9 25 68 88 80]
 [49 11 95 53 99]
 [54 67 99 15 35]
 [25 16 61 59 17]
 [10 94 87  3 28]]


In [13]:
# 查找所有大于50的订单
row_id, col_id = np.where(arr_new > 50)
print(f"所有大于50的订单的行索引: {row_id}")
print(f"所有大于50的订单的列索引: {col_id}")
print(f"所有大于50的订单的元素值: {arr_new[row_id, col_id]}")


所有大于50的订单的行索引: [0 0 0 1 1 1 2 2 2 3 3 4 4]
所有大于50的订单的列索引: [2 3 4 2 3 4 0 1 2 2 3 1 2]
所有大于50的订单的元素值: [68 88 80 95 53 99 54 67 99 61 59 94 87]
